In [ ]:
import numpy as np
import math

In [ ]:
a=1/math.sqrt(2)
b=1/math.sqrt(2)
v=np.array([a,b])
print(v)

[0.70710678 0.70710678]


In [ ]:
norm_check=a*a+b*b
print(norm_check)
if np.isclose(norm_check,1):
    print("Vector is normalized")
else:
    print("Vector is NOT normalized")


0.9999999999999998
Vector is normalized


In [ ]:
length=np.linalg.norm(v)
print("Length of vector:",length)

Length of vector: 0.9999999999999999


Section 2

In [ ]:
n=int(input("Enter dimension of vector: "))
A=[]
for i in range(n):
    A.append(float(input(f"Enter element {i+1}: ")))
A=np.array(A)
print("Vector A:", A)

Enter dimension of vector: 2
Enter element 1: 0.707
Enter element 2: 0.707
Vector A: [0.707 0.707]


In [ ]:
def check_normalized(v):
    return np.isclose(np.linalg.norm(v), 1)
print("Normalized:",check_normalized(A))

Normalized: False


In [ ]:
B=np.array(list(map(float, input("Enter vector B: ").split())))
dot=np.dot(A, B)
cross=np.cross(A,B)
print("Dot product:",dot)
print("Cross product:",cross)

Enter vector B: 1 0
Dot product: 0.707
Cross product: -0.707


/tmp/ipython-input-905787875.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cross=np.cross(A,B)


In [ ]:
def unit_vector(v):
    return v/np.linalg.norm(v)
print("Unit vector of A:", unit_vector(A))

Unit vector of A: [0.70710678 0.70710678]


Section 3

In [ ]:
r=int(input("Rows: "))
c=int(input("Cols: "))

M=[]
for i in range(r):
    row=list(map(float,input().split()))
    M.append(row)
M=np.array(M)
print(M)

Rows: 2
Cols: 2
1 2
3 4
[[1. 2.]
 [3. 4.]]


In [ ]:
print("Transpose:\n", M.T)
print("Determinant:", np.linalg.det(M))
print("Rank:", np.linalg.matrix_rank(M))
print("Trace:", np.trace(M))

Transpose:
 [[1. 3.]
 [2. 4.]]
Determinant: -2.0000000000000004
Rank: 2
Trace: 5.0


In [ ]:
values,vectors=np.linalg.eig(M)
print("Eigenvalues:", values)
print("Eigenvectors:\n", vectors)

print("Inverse:\n", np.linalg.inv(M))

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Section 4

In [ ]:
z=complex(input("Enter complex number (a+bj): "))
print(z)

Enter complex number (a+bj): 3+4j
(3+4j)


In [ ]:
print("Conjugate:", z.conjugate())

Conjugate: (3-4j)


In [ ]:
z2 = complex(input("Enter another complex number: "))
print("Addition:",z+z2)
print("Subtraction:",z-z2)
print("Multiplication:",z*z2)
print("Division:",z/z2)

Enter another complex number: 1+2j
Addition: (4+6j)
Subtraction: (2+2j)
Multiplication: (-5+10j)
Division: (2.2-0.4j)


In [ ]:
print("Magnitude:",abs(z))

Magnitude: 5.0
